# Generated by Django 3.1.7 on 2021-04-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection', models.CharField(max_length=60)),
                ('speed_download', models.IntegerField()),
                ('speed_upload', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
